apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-product-security-service
spec:
  selector:
    app: {{ .Release.Name }}-product-security
  ports:
      - protocol: TCP
        port: 9090
        targetPort: 9090
  type: LoadBalancer